apiVersion: apps/v1
kind: Deployment
metadata:
  name: undersoft-ssc-service-application-server
spec:
  selector:
    matchLabels:
      name: undersoft-ssc-service-application-server
  template:
    metadata:
      labels:
        name: undersoft-ssc-service-application-server
    spec:
      containers:
      - name: undersoft-ssc-service-application-server
        image: de.icr.io/undersoft/undersoftsscserviceapplicationserver:latest
---
apiVersion: v1
kind: Service
metadata:
  name: undersoft-ssc-service-application-server
spec:
  selector:
    name: undersoft-ssc-service-application-server
  ports:
  - port: 443
    targetPort: 15015
    name: public-https
  - port: 80
    targetPort: 16016
    name: public-http
  - port: 15015
    targetPort: 15015
    name: private-https
  - port: 16016
    targetPort: 16016
    name: private-http