apiVersion: v1
kind: Service
metadata:
  # This service is meant to be used by clients of the database. It exposes a ClusterIP that will
  # automatically load balance connections to the different database pods.
  name: undersoft-ssc-data-server
  labels:
    app: undersoft-ssc-data-server
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: grpc
  selector:
    app: undersoft-ssc-data-server
---
apiVersion: v1
kind: Service
metadata:
  # This service only exists to create DNS entries for each pod in the stateful
  # set such that they can resolve each other's IP addresses. It does not
  # create a load-balanced ClusterIP and should not be used directly by clients
  # in most circumstances.
  name: undersoft-ssc-data-server-private
  labels:
    app: undersoft-ssc-data-server
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: grpc
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: undersoft-ssc-data-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: undersoft-ssc-data-server
spec:
  selector:
    matchLabels:
      app: undersoft-ssc-data-server
  template:
    metadata:
      labels:
        app: undersoft-ssc-data-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - undersoft-ssc-data-server
              topologyKey: kubernetes.io/hostname
      containers:
      - name: undersoft-ssc-data-server
        image: de.icr.io/undersoft/undersoftsscdataserver:latest
        ports:
        - containerPort: 5432
          name: grpc
        volumeMounts:
         - name: undersoft-ssc-data-storage
           mountPath: /data
  volumeClaimTemplates:
   - metadata:
       name: undersoft-ssc-data-storage
     spec:
       accessModes:
         - "ReadWriteOnce"
       resources:
          requests:
              storage: 20Gi