apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: undersoft-ssc-data-server
spec:
  selector:
    matchLabels:
      name: undersoft-ssc-data-server
  template:
    metadata:
      labels:
        name: undersoft-ssc-data-server
    spec:
      containers:
      - name: undersoft-ssc-data-server
        image: de.icr.io/undersoft/undersoftsscdataserver:latest
        volumeMounts:
         - name: undersoft-ssc-data-storage
           mountPath: /data
  volumeClaimTemplates:
   - metadata:
       name: undersoft-ssc-data-storage
     spec:
       accessModes:
         - "ReadWriteOnce"
       resources:
          requests:
              storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: undersoft-ssc-data-server
spec:
  selector:
    name: undersoft-ssc-data-server
    type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: undersoft-ssc-service-server
spec:
  selector:
    matchLabels:
      name: undersoft-ssc-service-server
  template:
    metadata:
      labels:
        name: undersoft-ssc-service-server
    spec:
      containers:
      - name: undersoft-ssc-service-server
        image: de.icr.io/undersoft/undersoftsscserviceserver:latest
---
apiVersion: v1
kind: Service
metadata:
  name: undersoft-ssc-service-server
spec:
  selector:
    name: undersoft-ssc-service-server
  ports:
  - port: 25025
    targetPort: 25025
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: undersoft-ssc-service-application-server
spec:
  selector:
    matchLabels:
      name: undersoft-ssc-service-application-server
  template:
    metadata:
      labels:
        name: undersoft-ssc-service-application-server
    spec:
      containers:
      - name: undersoft-ssc-service-application-server
        image: de.icr.io/undersoft/undersoftsscserviceapplicationserver:latest
---
apiVersion: v1
kind: Service
metadata:
  name: undersoft-ssc-service-application-server
spec:
  selector:
    name: undersoft-ssc-service-application-server
  ports:
  - port: 15015
    targetPort: 15015
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: Undersoft.SSC.Ingress.Server
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: undersoft.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: Undersoft.SSC.Service.Application.Server
            port: 
              number: 80
